# Generated by Django 6.0 on 2025-12-25 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='bl_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vessel',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Job Creation'),
        ),
        migrations.AddField(
            model_name='job',
            name='place_discharge',
            field=models.CharField(blank=True, help_text='Place of Delivery/Final Destination', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='place_loading',
            field=models.CharField(blank=True, help_text='Place of Receipt', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='shipment_invoice_no',
            field=models.CharField(blank=True, help_text="Shipper's Invoice No", max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='transport_mode',
            field=models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], default='SEA', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_discharge',
            field=models.CharField(help_text='Port of Discharge (POD)', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_loading',
            field=models.CharField(help_text='Port of Loading (POL)', max_length=100),
        ),
    ]
