# Generated by Django 6.0 on 2025-12-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_bl_number_remove_job_vessel_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Gross Weight (KG)', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Net Weight (KG)', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_packages',
            field=models.IntegerField(default=0, help_text='Total No. of Packages'),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_discharge',
            field=models.CharField(blank=True, help_text='Place of Delivery', max_length=100),
        ),
    ]
