# Generated by Django 6.0 on 2025-12-25 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_gross_weight_job_net_weight_job_no_of_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_type', models.CharField(choices=[('CP', 'Cash Payment'), ('CR', 'Cash Receipt'), ('BP', 'Bank Payment'), ('BR', 'Bank Receipt')], max_length=2, verbose_name='Transaction Type')),
                ('party_name', models.CharField(help_text='Paid to / Received from', max_length=200)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, help_text='e.g. Bank Muscat', max_length=100)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.job')),
            ],
        ),
    ]
