# Generated by Django 6.0 on 2025-12-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_discharge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_loading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_discharge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_loading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipment_invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('CP', 'Cash Payment'), ('CR', 'Cash Receipt'), ('BP', 'Bank Payment'), ('BR', 'Bank Receipt')], max_length=2),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chargetype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.job')),
            ],
        ),
    ]
