# Generated by Django 6.0 on 2025-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chargetype_alter_job_gross_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
