# Generated by Django 6.0 on 2025-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoiceitem_amount_alter_invoiceitem_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='transport_document_no',
            field=models.CharField(blank=True, help_text='AWB, BL, or Consignment Note Number', max_length=100),
        ),
    ]
