# Generated by Django 6.0 on 2026-01-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_transaction_created_at_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
