# Generated by Django 6.0 on 2026-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
