# Generated by Django 5.1.4 on 2026-01-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_job_cbm_job_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipment_invoice_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
