# Generated by Django 5.1.4 on 2026-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_job_invoice_no_alter_job_shipment_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chargetype',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='container',
            name='seal',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='container',
            name='size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_weight',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='net_weight',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_discharge',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_loading',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_discharge',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_loading',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipment_invoice_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='transport_document_no',
            field=models.CharField(blank=True, help_text='AWB, BL, or Consignment Note Number', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='transport_mode',
            field=models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], default='SEA', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='vat_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='merchant',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(max_length=100),
        ),
    ]
