# Generated by Django 5.1.4 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_auditlog_action_alter_auditlog_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='transport_mode',
            field=models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], default='SEA', max_length=100),
        ),
    ]
