# Generated by Django 5.1.4 on 2026-01-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_job_invoice_no_alter_job_transport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shipment_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
