# Generated by Django 5.2.10 on 2026-02-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_party_transaction_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="party",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="party_name",
        ),
        migrations.AddField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="api.client",
            ),
        ),
    ]
