# Generated by Django 5.2.10 on 2026-02-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_transaction_party_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddField(
            model_name="job",
            name="is_invoiced",
            field=models.BooleanField(
                default=False,
                help_text="Marks job as invoiced and creates shadow entry",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="party_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="voucher_no",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["client", "date"], name="api_transac_client__a16de9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["party_name", "date"], name="api_transac_party_n_d911c1_idx"
            ),
        ),
    ]
