services:
  - type: web
    name: logistics-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: postgresql://postgres.vxrnpalmiodndzkwsckw:modernaccount1231@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
